
### Zindi mentorship program, competition 3
The objective of this competition is to create a forecast model to predict the number of incoming calls that Childline Kenya will receive per hour per day.

Your solution will help Childline manage its resources and staff their call center more efficiently, enabling them to better serve as many children as possible.

In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [71]:
train= pd.read_csv("train.csv")

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py:2714: DtypeWarning: Columns (12,13,14,18) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [72]:
train.head()

,calldate,cc_status,maincat,subcat1,casepriority,referal,caller_gender,caller_age,caller_county,child_age,child_gender,child_county,parent_age,parent_gender,parent_county,Abuser_Relationship,Neglector_Relationship,Perpetrator_Relationship,Physical abuser_Relationship
0,2016-01-01 07:26:47,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01 07:32:30,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-01 07:44:31,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-01 07:46:13,Closed,others,Unrelated to remit of Childline 116,Non Critical,NaN,Male,Adult,Nyeri,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-01 07:47:22,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
train.describe()

,calldate,cc_status,maincat,subcat1,casepriority,referal,caller_gender,caller_age,caller_county,child_age,child_gender,child_county,parent_age,parent_gender,parent_county,Abuser_Relationship,Neglector_Relationship,Perpetrator_Relationship,Physical abuser_Relationship
count,135988,135988,135988,135988,135988,1262,11548,10732,8667,3979,3992,3749,33,69,48,240,148,130,113
unique,132382,3,8,48,3,56,3,5,55,7,3,53,19,2,20,34,13,41,23
top,2016-04-01 10:21:00,Closed,non-interventional,Blank call,Non Critical,Childrens,Male,Adult,Nairobi,2016-11-15 00:00:00,Female,Nairobi,Adult,Male,Nairobi,Neighbor,Mother,Parents,Father
freq,9,134448,122835,71616,135730,601,6923,7884,1218,1451,2065,531,7,37,13,54,55,19,27

### Variables transformation

In [74]:
from datetime import datetime
train.calldate=pd.to_datetime(train.calldate)

In [75]:
train.head()

,calldate,cc_status,maincat,subcat1,casepriority,referal,caller_gender,caller_age,caller_county,child_age,child_gender,child_county,parent_age,parent_gender,parent_county,Abuser_Relationship,Neglector_Relationship,Perpetrator_Relationship,Physical abuser_Relationship
0,2016-01-01 07:26:47,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01 07:32:30,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-01 07:44:31,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-01 07:46:13,Closed,others,Unrelated to remit of Childline 116,Non Critical,NaN,Male,Adult,Nyeri,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-01 07:47:22,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
from datetime import datetime

Extract the month, hour and day from the variable date

In [77]:
#train['calldate'] = train['calldate'].apply(lambda x: datetime.strftime(x,"%Y-%m-%d-%H"))

In [78]:
train['year']=train['calldate'].apply(lambda x: datetime.strftime(x,"%Y"))
train['month']=train['calldate'].apply(lambda x: datetime.strftime(x,"%m"))
train['day']=train['calldate'].apply(lambda x: datetime.strftime(x,"%d"))
train['hour']=train['calldate'].apply(lambda x: datetime.strftime(x,"%H"))

In [80]:
train.head(5)

,calldate,cc_status,maincat,subcat1,casepriority,referal,caller_gender,caller_age,caller_county,child_age,...,parent_gender,parent_county,Abuser_Relationship,Neglector_Relationship,Perpetrator_Relationship,Physical abuser_Relationship,year,month,day,hour
0,2016-01-01 07:26:47,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2016,01,01,07
1,2016-01-01 07:32:30,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2016,01,01,07
2,2016-01-01 07:44:31,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2016,01,01,07
3,2016-01-01 07:46:13,Closed,others,Unrelated to remit of Childline 116,Non Critical,NaN,Male,Adult,Nyeri,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2016,01,01,07
4,2016-01-01 07:47:22,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2016,01,01,07

Now we need to count the number of call per hour per day

In [86]:
train['num_of_call']=1
data= (train.groupby(['month',"day", 'hour'])['num_of_call'].sum().reset_index())
train['num_of_call']=data['num_of_call']

In [89]:
train.head()

,calldate,cc_status,maincat,subcat1,casepriority,referal,caller_gender,caller_age,caller_county,child_age,...,parent_county,Abuser_Relationship,Neglector_Relationship,Perpetrator_Relationship,Physical abuser_Relationship,year,month,day,hour,num_of_call
0,2016-01-01 07:26:47,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2016,01,01,07,8.0
1,2016-01-01 07:32:30,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2016,01,01,07,41.0
2,2016-01-01 07:44:31,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2016,01,01,07,20.0
3,2016-01-01 07:46:13,Closed,others,Unrelated to remit of Childline 116,Non Critical,NaN,Male,Adult,Nyeri,NaN,...,NaN,NaN,NaN,NaN,NaN,2016,01,01,07,34.0
4,2016-01-01 07:47:22,Closed,non-interventional,Blank call,Non Critical,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2016,01,01,07,44.0

In [94]:
holiday=pd.read_csv('KenyaPublicHolidays2016.csv')

In [102]:
holiday['Public holidays Kenya 2017']

0            NaN
1           Date
2     2016/01/01
3     2016/03/25
4     2016/03/28
5     2016/05/01
6     2016/05/02
7     2016/06/01
8     2016/07/07
9     2016/09/11
10    2016/10/20
11    2016/12/12
12    2016/12/25
13    2016/12/26
14    2016/12/27
Name: Public holidays Kenya 2017, dtype: object

In [104]:
hol_month=["01","03","03","05","05", "06","07","09","10","12","12","12","12"]
hol_day=  ["01","25","28", "01","02","01","07","11","20","12","25","26","27"]

In [111]:
train['is_holyday']=1
for k in range(train.shape[0]):
    for i, j in zip(hol_month,hol_day):
      
        if train['month'][k]==i and train['day'][k]==j:
            train['is_holyday'][k]="yes"

        else:
            train['is_holyday'][k]="no"

/usr/lib/python3/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/aimsg/.local/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
/usr/lib/python3/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':